rootProject.name = 'calm-springs-engine'

include 'cse'
include 'cse-codec-pdf'
include 'cse-codec-video'
include 'cse-media'
include 'cse-codec-image'
include 'cse-codec-audio'
include 'cse-security'
include 'cse-content'
include 'cse-themes'
include 'cse-apps'
include 'cse-transfer'
include 'cse-install'
include 'cse-core'
include 'cse-dal-core'
include 'cse-db-mongo'
include 'cse-db-postgres'
include 'app-setup'
include 'app-admin'
include 'app-login'
include 'app-projects'
include 'theme-thymeleaf-modern'
include 'theme-thymeleaf-2000s'
include 'theme-js-client'
