spring.main.banner-mode=off
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
spring.servlet.multipart.file-size-threshold=1MB
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
