plugins {
    id 'java-library'
}

apply from: rootProject.file('gradle/cse-db.gradle')

description = 'CSE MongoDB adapter (MongoTemplate)'

dependencies {
    api project(':cse-db-api')
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework:spring-web'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
