plugins {
    id 'java-library'
}

apply from: rootProject.file('gradle/cse-db.gradle')

description = 'CSE MongoDB adapter (MongoTemplate)'

dependencies {
    api project(':cse-content')
    api project(':cse-media')
    api project(':cse-security')
    api project(':cse-themes')
    api project(':cse-apps')
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework:spring-web'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
