java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

ext {
    springBootVersion = '3.5.8'
}

dependencies {
    api platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
}

tasks.named('test') {
    useJUnitPlatform()
}
